name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install packages
      shell: bash
      run: npm install --global yarn && yarn install:ci
