# Validation steps required before a build occurs. Not designed to replace the CI test workflow
name: Pandaria Build Test

on:
  # This tells GH that the workflow is reusable 
  workflow_call:

jobs:
  unit-test:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/unit-tests

  i18n:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    needs:
      - unit-test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run i18n lint
        uses: ./.github/actions/i18n-lint

  lint:
    runs-on: repo-dashboard-runner-k8s
    container: ubuntu:22.04
    needs:
      - i18n
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run lint
        uses: ./.github/actions/lint
