# Validation steps required before a build occurs. Not designed to replace the CI test workflow
name: Pandaria Build Test

on:
  # This tells GH that the workflow is reusable 
  workflow_call:

jobs:
  # unit-test:
  #   runs-on: repo-dashboard-runner-k8s
  #   container: ubuntu:24.04
  #   steps:
  #     - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
  #       with:
  #         fetch-depth: 1

  #     - name: Run tests
  #       uses: ./.github/actions/unit-tests

  lint:
    runs-on: repo-dashboard-runner-k8s
    container: node:24
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1
      - name: Install packages
        shell: bash
        run: npx yarn install:ci

      - name: Run i18n linters
        shell: bash
        run: npx yarn lint-l10n

      - name: Run linters
        shell: bash
        run: npx yarn lint
      

  
